In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [77]:
data_path = 'C:/Users/aderson.medeiros/Documents/aderson/estudo/dataScience/udemy/deep_learning_az/part1-ann/'
dataset = pd.read_csv(data_path+'source/Churn_Modelling.csv')

In [78]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [79]:
#Encoding categorical variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [80]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:,2])

In [94]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('onehot', OneHotEncoder(), [1])])
result = ct.fit_transform(X)
print(np.concatenate((X, result), axis=1))

[[619 0 0 ... 1.0 0.0 0.0]
 [608 2 0 ... 0.0 0.0 1.0]
 [502 0 0 ... 1.0 0.0 0.0]
 ...
 [709 0 0 ... 1.0 0.0 0.0]
 [772 1 1 ... 0.0 1.0 0.0]
 [792 0 0 ... 1.0 0.0 0.0]]


C:\Users\aderson.medeiros\Documents\aderson\estudo\dataScience\udemy\deep_learning_az\deeplaz\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [91]:
type(result)

numpy.ndarray

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=42)